### ISSUE TITLE
Not possible to run lightning_web.py

### ISSUE THREAD

**Issue by AbsolutK** [pcfens/RPi-AS3935-Web#2]
I get below error and even after making sure the requirements.txt is installed with the appropriate versions listed, it still won't work. Can you help me out here please?

pi@raspberrypi:~/Lightning/RPi-AS3935-Web-master $ sudo python lightning_web.py 
lightning_web.py:3: ExtDeprecationWarning: Importing flask.ext.socketio is deprecated, use flask_socketio instead.
  from flask.ext.socketio import SocketIO, emit
Traceback (most recent call last):
  File "lightning_web.py", line 3, in <module>
    from flask.ext.socketio import SocketIO, emit
  File "/usr/lib/python2.7/dist-packages/flask/exthook.py", line 110, in load_module
    raise ImportError('No module named %s' % fullname)
ImportError: No module named flask.ext.socketio

**Comment by pcfens** [comment]
What's the output of `pip freeze`? I suspect that you installed the newest version of Flask-SocketIO which doesn't work on the old code here (the version it expects is a little over 3 years old).

I've personally switched to a new way of pushing to a web browser, but will try to get my sensor wired up to the Pi and update the code at some point (though PRs are always welcome :smile:)

**Comment by AbsolutK** [comment]
Thanks for your answer. I was sure my module versions were OK, however as I need to launch the webserver as sudo it appears some modules weren't installed under sudo (only local). Solved!
