### ISSUE TITLE
Sensitivity problems not really an issue as such.

### ISSUE THREAD

**Issue by TheMetMan** [pcfens/RPi-AS3935-Web#3]
I have set up the AS3935 on a PiZero up above the gable end of my house. I live in a remote area near the coast in SW Ireland, so very little electrical disturbance.
I am getting lots of strikes even on a clear day with no clouds. I am keeping an eye on Met Eireann for strikes.
I have sensor.set_indoors(False) and I guess looking at the code I need to raise the noise floor. 
From your experience have you found a setting which works for you?
I am going to try a setting of 3 (I see the max is 7) and if that is too much reduce it. I also realise that it will take a good while to get it correct because we do not get a lot of lightning here, but that is all part of the fun.
Regards

**Comment by pcfens** [comment]
I've re-worked my setup and don't use this code much anymore, but I think before I switched I was moving the noise floor up and down dynamically based on how noisy things seem to be. I think I was doing something like 3 interrupts for noise in 15 seconds would trigger raising it by one, and nothing at all for a minute or two would lower it by one.

Now I've arbitrarily set it at 3 and count everything to feed in to [Prometheus](https://prometheus.io/), but I only graph the strikes and distance parts.

Sorry I don't have a magic answer, but I hope that helps.

**Comment by TheMetMan** [comment]
OK, I will look at all that, and thank you so much for responding so quickly.
Regards
